# Generated by Django 2.1.15 on 2021-06-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classavails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classavails',
            name='courseNumber',
        ),
        migrations.RemoveField(
            model_name='classavails',
            name='department',
        ),
        migrations.AddField(
            model_name='classavails',
            name='course',
            field=models.CharField(default='ABC 000', max_length=10),
        ),
        migrations.AddField(
            model_name='classavails',
            name='credits',
            field=models.CharField(default='-1', max_length=25),
        ),
        migrations.AddField(
            model_name='classavails',
            name='curEnrolled',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='classavails',
            name='curWaitlisted',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='classavails',
            name='dates',
            field=models.CharField(default='XXX', max_length=50),
        ),
        migrations.AddField(
            model_name='classavails',
            name='days',
            field=models.CharField(default=-1, max_length=10),
        ),
        migrations.AddField(
            model_name='classavails',
            name='instructor',
            field=models.CharField(default='XXXXXXXXX', max_length=50),
        ),
        migrations.AddField(
            model_name='classavails',
            name='location',
            field=models.CharField(default='XXX', max_length=50),
        ),
        migrations.AddField(
            model_name='classavails',
            name='seatsAvail',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='classavails',
            name='section',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='classavails',
            name='time',
            field=models.CharField(default='XX-XX', max_length=100),
        ),
        migrations.AddField(
            model_name='classavails',
            name='title',
            field=models.CharField(default='XXXXXX', max_length=100),
        ),
        migrations.AddField(
            model_name='classavails',
            name='waitlistAvailable',
            field=models.IntegerField(default=-1),
        ),
    ]
